//
// ChatCompletionRequestSystemMessageContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The contents of the system message. */
public enum ChatCompletionRequestSystemMessageContent: Codable, JSONEncodable, Hashable {
    case typeString(String)
    case type[ChatCompletionRequestSystemMessageContentPart]([ChatCompletionRequestSystemMessageContentPart])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeString(let value):
            try container.encode(value)
        case .type[ChatCompletionRequestSystemMessageContentPart](let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else if let value = try? container.decode([ChatCompletionRequestSystemMessageContentPart].self) {
            self = .type[ChatCompletionRequestSystemMessageContentPart](value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ChatCompletionRequestSystemMessageContent"))
        }
    }
}

