//
// RealtimeServerEventConversationCreated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returned when a conversation is created. Emitted right after session creation. */
public struct RealtimeServerEventConversationCreated: Codable, JSONEncodable, Hashable {

    /** The unique ID of the server event. */
    public var eventId: String
    /** The event type, must be \"conversation.created\". */
    public var type: String
    public var conversation: RealtimeServerEventConversationCreatedConversation

    public init(eventId: String, type: String, conversation: RealtimeServerEventConversationCreatedConversation) {
        self.eventId = eventId
        self.type = type
        self.conversation = conversation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId = "event_id"
        case type
        case conversation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventId, forKey: .eventId)
        try container.encode(type, forKey: .type)
        try container.encode(conversation, forKey: .conversation)
    }
}

