//
// RealtimeClientEventResponseCancel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Send this event to cancel an in-progress response. The server will respond with a &#x60;response.cancelled&#x60; event or an error if there is no response to cancel. */
public struct RealtimeClientEventResponseCancel: Codable, JSONEncodable, Hashable {

    /** Optional client-generated ID used to identify this event. */
    public var eventId: String?
    /** The event type, must be `response.cancel`. */
    public var type: String

    public init(eventId: String? = nil, type: String) {
        self.eventId = eventId
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId = "event_id"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventId, forKey: .eventId)
        try container.encode(type, forKey: .type)
    }
}

